#!/usr/bin/env bash
# This script transfers a file from a client to a server using scp.

# Check if all required parameters are provided
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Assign parameters to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file to the server
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "${USERNAME}@${IP}:~/"
